//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Img_src { get; set; }
        public string Content { get; set; }
        public int House_categeryId { get; set; }
    
        public virtual House_categery House_categery { get; set; }
    }
}
